# Generated by Django 5.1.1 on 2024-10-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_alter_ticket_order_alter_ticket_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
